name: Claude Actions

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  claude-response:
    if: contains(github.event.issue.title, '@claude') || contains(github.event.issue.body, '@claude') || contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        ref: main
        
    - name: Setup directories
      run: |
        # 不要なファイル・ディレクトリを削除
        rm -rf _posts
        rm -rf posts
        rm -f faq.md
        rm -f courses.md
        rm -f about.md
        rm -f blog-*.md
        echo "Cleaned up unnecessary files and directories"
        
    - name: Extract request
      id: request
      run: |
        if [ "${{ github.event_name }}" = "issues" ]; then
          TEXT="${{ github.event.issue.title }} ${{ github.event.issue.body }}"
        else
          TEXT="${{ github.event.comment.body }}"
        fi
        REQUEST=$(echo "$TEXT" | sed 's/.*@claude *//g' | head -1)
        echo "text=$REQUEST" >> $GITHUB_OUTPUT
        echo "Request: $REQUEST"
        
    - name: Call Claude API
      id: claude
      run: |
        REQUEST="${{ steps.request.outputs.text }}"
        echo "Calling Claude with: $REQUEST"
        
        RESPONSE=$(curl -s -X POST https://api.anthropic.com/v1/messages \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${{ secrets.ANTHROPIC_API_KEY }}" \
          -H "anthropic-version: 2023-06-01" \
          -d "{
            \"model\": \"claude-3-sonnet-20240229\",
            \"max_tokens\": 1000,
            \"messages\": [{
              \"role\": \"user\", 
              \"content\": \"ヘーホー学舎のウェブサイト用コンテンツ作成: $REQUEST\"
            }]
          }")
        
        CONTENT=$(echo "$RESPONSE" | jq -r '.content[0].text // "エラー: コンテンツを生成できませんでした"')
        echo "Generated content: $CONTENT"
        
        {
          echo "content<<ENDOFCONTENT"
          echo "$CONTENT"
          echo "ENDOFCONTENT"
        } >> $GITHUB_OUTPUT
        
    - name: Update content
      run: |
        CONTENT="${{ steps.claude.outputs.content }}"
        REQUEST="${{ steps.request.outputs.text }}"
        
        if echo "$REQUEST" | grep -qi "faq"; then
          # FAQセクションをindex.mdに追加
          echo "" >> index.md
          echo "## FAQ" >> index.md
          echo "" >> index.md
          echo "$CONTENT" >> index.md
          
        elif echo "$REQUEST" | grep -qi "講座\|course"; then
          # 講座セクションをindex.mdに追加
          echo "" >> index.md
          echo "## 講座情報" >> index.md
          echo "" >> index.md
          echo "$CONTENT" >> index.md
          
        elif echo "$REQUEST" | grep -qi "トップ\|index\|ホーム\|メイン\|更新"; then
          # index.mdを完全に置き換え
          echo "---" > index.md
          echo "layout: home" >> index.md
          echo "---" >> index.md
          echo "" >> index.md
          echo "$CONTENT" >> index.md
          
        else
          # その他の内容もindex.mdに追加
          echo "" >> index.md
          echo "## 追加情報" >> index.md
          echo "" >> index.md
          echo "$CONTENT" >> index.md
        fi
        
        echo "Updated: index.md"
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Claude Actions"
        git pull origin main
        git add .
        git commit -m "Update content via Claude" || echo "No changes"
        git push origin main
        
    - name: Comment
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments" \
          -d '{"body":"🤖 コンテンツを更新しました！数分後にサイトに反映されます。"}'
