name: Simple Claude Actions

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  claude-response:
    if: contains(github.event.issue.title, '@claude') || contains(github.event.issue.body, '@claude') || contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Clean files
      run: |
        rm -rf _posts posts
        rm -f faq.md courses.md about.md blog-*.md
        
    - name: Get request
      id: req
      run: |
        if [ "${{ github.event_name }}" = "issues" ]; then
          # Issue本文をそのまま使用
          echo '${{ github.event.issue.body }}' > request.txt
        else
          echo '${{ github.event.comment.body }}' > request.txt
        fi
        echo "file=request.txt" >> $GITHUB_OUTPUT
        
    - name: Call Claude
      run: |
        REQUEST_FILE="${{ steps.req.outputs.file }}"
        REQUEST_CONTENT=$(cat "$REQUEST_FILE")
        
        curl -s -X POST https://api.anthropic.com/v1/messages \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${{ secrets.ANTHROPIC_API_KEY }}" \
          -H "anthropic-version: 2023-06-01" \
          -d "{
            \"model\": \"claude-3-sonnet-20240229\",
            \"max_tokens\": 2000,
            \"messages\": [{
              \"role\": \"user\", 
              \"content\": \"あなたはWebサイトのコンテンツライターです。以下のリクエストに基づいて、平放学舎（ヘーホー学舎）のWebサイト用のコンテンツを作成してください。\\n\\nリクエストに含まれている情報をそのまま使用して、魅力的なマークダウン形式のWebページを作成してください。見出し、箇条書き、段落などを適切に使用してください。\\n\\n出力は完成したWebページのコンテンツのみを返してください。説明や追加の質問は不要です。\\n\\n---\\n\\n$REQUEST_CONTENT\"
            }]
          }" | jq -r '.content[0].text // "エラー: コンテンツを生成できませんでした"' > content.txt
        
    - name: Update index
      run: |
        echo "---" > index.md
        echo "layout: home" >> index.md
        echo "---" >> index.md
        echo "" >> index.md
        cat content.txt >> index.md
        
    - name: Commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Claude Actions"
        
        # 最新の変更を取得
        git fetch origin
        git rebase origin/main || git reset --hard origin/main
        
        # ファイルを再度更新（rebaseで消えた場合に備えて）
        echo "---" > index.md
        echo "layout: home" >> index.md
        echo "---" >> index.md
        echo "" >> index.md
        cat content.txt >> index.md
        
        git add .
        git commit -m "Update by Claude" || echo "No changes"
        git push origin main
        
    - name: Comment
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments" \
          -d '{"body":"🤖 更新完了！"}'
